## Copyright (C) 2016 Thierry Rascle <thierr26@free.fr>
## MIT license. Please refer to the LICENSE file.
## Author: Thierry Rascle <thierr26@free.fr>

function [s, default] = command_stru_and_default

    default = 'configure';
    s = struct(...
        default, @scalar_num_arg_or_none, ...
        'quit', @scalar_num_arg_or_none, ...
        'get_config', @scalar_num_arg_or_none, ...
        'connect', @() true, ...
        'disp', @(varargin) scalar_num_arg_or_none(varargin{1 : end - 1}), ...
        'dispf', @outman_printf_args, ...
        'printf', @outman_printf_args, ...
        'errorf', @outman_printf_args, ...
        'warningf', @outman_printf_args, ...
        'infof', @outman_printf_args, ...
        'logf', @outman_printf_args, ...
        'logtimef', @outman_printf_args, ...
        'init_progress', @outman_init_prog_args, ...
        'update_progress', @outman_update_prog_args, ...
        'shift_progress', ...
            @(varargin) nargin == 3 && scalar_num_args(varargin{:}), ...
        'terminate_progress', ...
            @(varargin) nargin == 2 && scalar_num_args(varargin{:}), ...
        'cancel_progress', ...
            @(varargin) nargin == 2 && scalar_num_args(varargin{:}), ...
        'get_config_origin', @scalar_num_arg_or_none, ...
        'get_mmi_variant', @scalar_num_arg_or_none, ...
        'get_log_file_name', @scalar_num_arg_or_none);

endfunction
