## Copyright (C) 2016 Thierry Rascle <thierr26@free.fr>
## MIT license. Please refer to the LICENSE file.
## Author: Thierry Rascle <thierr26@free.fr>

function [s, default] = command_stru_and_default

    default = 'all';
    s = struct(...
        'quit', @() true, ...
        'configure', @() true, ...
        default, @string_or_cellstr_arg_or_none, ...
        'encoding', @string_or_cellstr_arg_or_none, ...
        'code', @string_or_cellstr_arg_or_none, ...
        'dependencies', @string_or_cellstr_arg_or_none);

endfunction
