## Copyright (C) 2016 Thierry Rascle <thierr26@free.fr>
## MIT license. Please refer to the LICENSE file.

## -*- texinfo -*-
## @deftypefn {Function File} ignored_dir_list ()
##
## Return the list of directory names that are ignored by default by
## @code{find_files}.
##
## The list has been built based on the ignore list used by the "ack" software.
## See file ConfigDefault.pm in ack repository
## (https://github.com/petdance/ack2).
##
## @seealso{find_files}
## @end deftypefn

## Author: Thierry Rascle <thierr26@free.fr>

function c = ignored_dir_list

    c = {...
        '.bzr', ...
        '.cdv', ...
        '.git', ...
        '.hg', ...
        '.pc', ...
        '.svn', ...
        '_MTN', ...
        'CVS', ...
        'RCS', ...
        'SCCS', ...
        '_darcs', ...
        '_sgbak', ...
        '.metadata'};

endfunction
