## Copyright (C) 2016 Thierry Rascle <thierr26@free.fr>
## MIT license. Please refer to the LICENSE file.

## -*- texinfo -*-
## @deftypefn {Function File} {@var{list} =} ignored_dir_list ()
##
## List of directories that are ignored by default by @code{find_files}.
##
## @code{@var{list} = ignored_dir_list ()} returns a cell array of strings
## containing the names of the directories that are ignored by default by
## function @code{find_files}.
##
## @seealso{find_files}
## @end deftypefn

## Author: Thierry Rascle <thierr26@free.fr>

function list = ignored_dir_list

    # The list has been built based on the ignore list used by the "ack"
    # software.  See file ConfigDefault.pm in ack repository
    # (https://github.com/petdance/ack2).

    list = {...
        '.bzr', ...
        '.cdv', ...
        '.git', ...
        '.hg', ...
        '.pc', ...
        '.svn', ...
        '_MTN', ...
        'CVS', ...
        'RCS', ...
        'SCCS', ...
        '_darcs', ...
        '_sgbak', ...
        '.metadata'};

endfunction
