## Copyright (C) 2016 Thierry Rascle <thierr26@free.fr>
## MIT license. Please refer to the LICENSE file.
## Author: Thierry Rascle <thierr26@free.fr>

function s = alias_stru

    s = struct(...
        'q', {{'quit'}}, ...
        'exit', {{'quit'}}, ...
        'bye', {{'quit'}}, ...
        'clear', {{'quit'}}, ...
        'a', {{'add_to_path'}}, ...
        't', {{'run_test'}}, ...
        'ta', {{'run_all_tests'}}, ...
        'l', {{'list_declared_deps'}}, ...
        'f', {{'refresh_cache'}}, ...
        'get_config', {{'configure'}});

endfunction
